const canvas = document.querySelector('#game');
const context = canvas.getContext('2d');
const overlay = document.querySelector('#overlay');
const overlayTitle = document.querySelector('#overlay-title');
const overlayCopy = document.querySelector('#overlay-copy');
const startButton = document.querySelector('#start');
const restartButton = document.querySelector('#restart');
const message = document.querySelector('#message');
const lootOutput = document.querySelector('#loot');
const catStatus = document.querySelector('#cat-status');
const objective = document.querySelector('#objective');

const walls = [{ x: 0, y: 0, width: 800, height: 22 }, { x: 0, y: 498, width: 800, height: 22 }, { x: 0, y: 0, width: 22, height: 520 }, { x: 778, y: 0, width: 22, height: 520 }, { x: 300, y: 115, width: 200, height: 42 }, { x: 300, y: 157, width: 42, height: 150 }, { x: 458, y: 157, width: 42, height: 150 }];
const hidingSpots = [{ x: 74, y: 145, width: 100, height: 62, name: 'mobiletto' }, { x: 620, y: 350, width: 102, height: 62, name: 'dispensa' }];
const foodStart = [{ x: 230, y: 90, icon: '🧀', name: 'formaggio' }, { x: 600, y: 120, icon: '🍪', name: 'biscotto' }, { x: 210, y: 390, icon: '🍎', name: 'mela' }];
const patrol = [{ x: 610, y: 270 }, { x: 680, y: 270 }, { x: 680, y: 440 }, { x: 560, y: 440 }];
const state = { phase: 'ready', lastTime: 0, keys: new Set(), score: 0, hidden: false, catIndex: 0, catTarget: 1, catAlert: 0, mouse: { x: 110, y: 420, radius: 15 }, cat: { x: 610, y: 270, radius: 18 }, foods: [] };

function resetState() { state.phase = 'ready'; state.score = 0; state.hidden = false; state.catIndex = 0; state.catTarget = 1; state.catAlert = 0; state.mouse = { x: 110, y: 420, radius: 15 }; state.cat = { x: 610, y: 270, radius: 18 }; state.foods = foodStart.map((food) => ({ ...food, collected: false })); updateHud(); draw(); }
function updateHud() { const collected = state.foods.filter((food) => food.collected).length; lootOutput.textContent = `${collected} / ${state.foods.length}`; catStatus.textContent = state.hidden ? 'Non mi vede' : state.catAlert > 0 ? 'Ha visto qualcosa!' : 'Pisolino'; objective.textContent = collected === state.foods.length ? 'Torna alla tana' : 'Ruba tutto'; }
function distance(first, second) { return Math.hypot(first.x - second.x, first.y - second.y); }
function circleRectCollision(circle, rect) { const closestX = Math.max(rect.x, Math.min(circle.x, rect.x + rect.width)); const closestY = Math.max(rect.y, Math.min(circle.y, rect.y + rect.height)); return distance(circle, { x: closestX, y: closestY }) < circle.radius; }
function canMove(next) { return next.x > 38 && next.x < 762 && next.y > 38 && next.y < 482 && !walls.slice(4).some((wall) => circleRectCollision(next, wall)); }
function nearestHidingSpot() { return hidingSpots.find((spot) => circleRectCollision(state.mouse, { ...spot, x: spot.x - 20, y: spot.y - 20, width: spot.width + 40, height: spot.height + 40 })); }
function interact() { if (state.phase !== 'playing') return; if (state.hidden) { state.hidden = false; message.textContent = 'Fuori dal mobiletto. Piano!'; updateHud(); return; } const hidingSpot = nearestHidingSpot(); if (hidingSpot) { state.hidden = true; message.textContent = `Nascosto nel ${hidingSpot.name}.`; updateHud(); return; } const food = state.foods.find((item) => !item.collected && distance(state.mouse, item) < 34); if (food) { food.collected = true; state.score += 1; message.textContent = `Gnam! Hai rubato il ${food.name}.`; updateHud(); } }
function startGame() { resetState(); state.phase = 'playing'; overlay.classList.add('hidden'); message.textContent = 'Muoviti piano. Il gatto pattuglia...'; canvas.focus(); state.lastTime = performance.now(); requestAnimationFrame(loop); }
function finish(won) { if (state.phase !== 'playing') return; state.phase = won ? 'won' : 'lost'; overlayTitle.textContent = won ? 'Furto riuscito!' : 'Beccato con le zampe nel sacco!'; overlayCopy.textContent = won ? 'Hai portato tutto nella tana. Il gatto sospetta del biscotto.' : 'Il gatto ti ha visto. Riprova usando meglio i mobiletti.'; startButton.textContent = 'Gioca ancora →'; overlay.classList.remove('hidden'); message.textContent = won ? 'Casa dolce casa.' : 'Missione fallita.'; }
function update(delta) { const speed = 155 * delta; const direction = { x: 0, y: 0 }; if (state.keys.has('ArrowLeft') || state.keys.has('a')) direction.x -= 1; if (state.keys.has('ArrowRight') || state.keys.has('d')) direction.x += 1; if (state.keys.has('ArrowUp') || state.keys.has('w')) direction.y -= 1; if (state.keys.has('ArrowDown') || state.keys.has('s')) direction.y += 1; if (direction.x || direction.y) { const length = Math.hypot(direction.x, direction.y); const next = { ...state.mouse, x: state.mouse.x + direction.x / length * speed, y: state.mouse.y + direction.y / length * speed }; if (canMove(next)) state.mouse = next; }
  if (state.hidden) { updateHud(); return; }
  const target = patrol[state.catTarget]; const catSpeed = state.catAlert > 0 ? 87 : 43; const catDistance = distance(state.cat, state.mouse); if (catDistance < 145) state.catAlert = 2.5; else state.catAlert = Math.max(0, state.catAlert - delta); const destination = state.catAlert > 0 ? state.mouse : target; const vector = { x: destination.x - state.cat.x, y: destination.y - state.cat.y }; const length = Math.hypot(vector.x, vector.y) || 1; state.cat.x += vector.x / length * catSpeed * delta; state.cat.y += vector.y / length * catSpeed * delta; if (distance(state.cat, target) < 8 && state.catAlert <= 0) state.catTarget = (state.catTarget + 1) % patrol.length; if (distance(state.cat, state.mouse) < 26) finish(false); const collected = state.foods.every((food) => food.collected); const den = { x: 92, y: 70 }; if (collected && distance(state.mouse, den) < 42) finish(true); updateHud(); }
function draw() { context.clearRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#e3d09f'; context.fillRect(0, 0, canvas.width, canvas.height); drawRoom(); drawEntities(); }
function drawRoom() { context.fillStyle = '#c5a979'; walls.forEach((wall) => context.fillRect(wall.x, wall.y, wall.width, wall.height)); context.fillStyle = 'rgba(255,255,255,.18)'; for (let x = 36; x < 770; x += 48) for (let y = 38; y < 482; y += 48) context.fillRect(x, y, 2, 2); context.fillStyle = '#977b50'; context.fillRect(330, 145, 140, 125); context.fillStyle = '#ad8e5e'; context.fillRect(347, 162, 106, 92); context.fillStyle = '#7f6243'; context.fillRect(84, 150, 80, 42); context.fillRect(630, 355, 84, 42); context.font = '700 12px Space Mono, monospace'; context.fillStyle = '#6f543c'; context.fillText('TANA', 67, 82); context.fillText('NASCONDIGLIO', 76, 137); context.fillText('DISPENSA', 635, 342); context.fillStyle = '#f5e9c4'; context.fillRect(61, 49, 85, 48); context.strokeStyle = '#9d7951'; context.strokeRect(61, 49, 85, 48); context.font = '30px serif'; context.fillText('🕳️', 86, 84); }
function drawEntities() { state.foods.forEach((food) => { if (!food.collected) { context.font = '27px serif'; context.fillText(food.icon, food.x - 14, food.y + 10); context.strokeStyle = '#fff8d4'; context.lineWidth = 2; context.beginPath(); context.arc(food.x, food.y, 21, 0, Math.PI * 2); context.stroke(); } }); context.font = '32px serif'; context.globalAlpha = state.hidden ? .3 : 1; context.fillText('🐭', state.mouse.x - 17, state.mouse.y + 11); context.globalAlpha = 1; context.fillText('🐱', state.cat.x - 18, state.cat.y + 12); if (state.catAlert > 0 && !state.hidden) { context.fillStyle = '#f36d59'; context.font = '700 21px sans-serif'; context.fillText('!', state.cat.x + 15, state.cat.y - 18); } }
function loop(timestamp) { if (state.phase !== 'playing') return; const delta = Math.min((timestamp - state.lastTime) / 1000, .05); state.lastTime = timestamp; update(delta); draw(); requestAnimationFrame(loop); }

document.addEventListener('keydown', (event) => { const key = event.key.length === 1 ? event.key.toLowerCase() : event.key; if (['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'a', 'd', 'w', 's'].includes(key)) { event.preventDefault(); state.keys.add(key); } if (key === 'e' || key === ' ') { event.preventDefault(); interact(); } if (key === 'r') startGame(); });
document.addEventListener('keyup', (event) => { const key = event.key.length === 1 ? event.key.toLowerCase() : event.key; state.keys.delete(key); });
document.querySelectorAll('.touch button').forEach((button) => { const key = button.dataset.key; button.addEventListener('pointerdown', () => state.keys.add(key)); button.addEventListener('pointerup', () => state.keys.delete(key)); button.addEventListener('pointerleave', () => state.keys.delete(key)); });
startButton.addEventListener('click', startGame); restartButton.addEventListener('click', startGame); resetState();